auto:        true
safe:        true
server:      true
server_port: 4000
base-url:    .
url:         http://localhost:4000/

source:      .
destination: ./_site
plugins:     ./_plugins


lsi:         false
permalink:   /docs/:categories/:title
pygments:    true
markdown:    redcarpet